package gov.cms.fqhc_pricer;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CalculationHelper implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Double gafs2017rate;

	private java.lang.Double gafs2018rate;

	private java.lang.Double gafs2018revisedrate;

	private java.lang.Double gafs2019rate;

	public CalculationHelper() {
	}

	public java.lang.Double getGafs2017rate() {
		return this.gafs2017rate;
	}

	public void setGafs2017rate(java.lang.Double gafs2017rate) {
		this.gafs2017rate = gafs2017rate;
	}

	public java.lang.Double getGafs2018rate() {
		return this.gafs2018rate;
	}

	public void setGafs2018rate(java.lang.Double gafs2018rate) {
		this.gafs2018rate = gafs2018rate;
	}

	public java.lang.Double getGafs2018revisedrate() {
		return this.gafs2018revisedrate;
	}

	public void setGafs2018revisedrate(java.lang.Double gafs2018revisedrate) {
		this.gafs2018revisedrate = gafs2018revisedrate;
	}

	public java.lang.Double getGafs2019rate() {
		return this.gafs2019rate;
	}

	public void setGafs2019rate(java.lang.Double gafs2019rate) {
		this.gafs2019rate = gafs2019rate;
	}

	public CalculationHelper(java.lang.Double gafs2017rate,
			java.lang.Double gafs2018rate,
			java.lang.Double gafs2018revisedrate, java.lang.Double gafs2019rate) {
		this.gafs2017rate = gafs2017rate;
		this.gafs2018rate = gafs2018rate;
		this.gafs2018revisedrate = gafs2018revisedrate;
		this.gafs2019rate = gafs2019rate;
	}

}