package gov.cms.fqhc_pricer;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Claim implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String providerNumber;
	private java.lang.String carrier;
	private java.lang.String locality;
	@org.kie.api.definition.type.Description("MA-PLAN-AMT")
	private java.lang.Double maPlanAmount;
	@org.kie.api.definition.type.Description("SRVC-FROM-DATE")
	private java.util.Date serviceFromDate;
	private java.util.Date serviceThroughDate;

	private java.lang.Double totalClaimPayment;

	private java.lang.Double totalMedicareReimbursement;

	private java.lang.String claimReturnCode;

	private java.lang.Double totalClaimCoinsurance;

	public Claim() {
	}

	public java.lang.String getProviderNumber() {
		return this.providerNumber;
	}

	public void setProviderNumber(java.lang.String providerNumber) {
		this.providerNumber = providerNumber;
	}

	public java.lang.String getCarrier() {
		return this.carrier;
	}

	public void setCarrier(java.lang.String carrier) {
		this.carrier = carrier;
	}

	public java.lang.String getLocality() {
		return this.locality;
	}

	public void setLocality(java.lang.String locality) {
		this.locality = locality;
	}

	public java.lang.Double getMaPlanAmount() {
		return this.maPlanAmount;
	}

	public void setMaPlanAmount(java.lang.Double maPlanAmount) {
		this.maPlanAmount = maPlanAmount;
	}

	public java.util.Date getServiceFromDate() {
		return this.serviceFromDate;
	}

	public void setServiceFromDate(java.util.Date serviceFromDate) {
		this.serviceFromDate = serviceFromDate;
	}

	public java.util.Date getServiceThroughDate() {
		return this.serviceThroughDate;
	}

	public void setServiceThroughDate(java.util.Date serviceThroughDate) {
		this.serviceThroughDate = serviceThroughDate;
	}

	public java.lang.Double getTotalClaimPayment() {
		return this.totalClaimPayment;
	}

	public void setTotalClaimPayment(java.lang.Double totalClaimPayment) {
		this.totalClaimPayment = totalClaimPayment;
	}

	public java.lang.Double getTotalMedicareReimbursement() {
		return this.totalMedicareReimbursement;
	}

	public void setTotalMedicareReimbursement(
			java.lang.Double totalMedicareReimbursement) {
		this.totalMedicareReimbursement = totalMedicareReimbursement;
	}

	public java.lang.String getClaimReturnCode() {
		return this.claimReturnCode;
	}

	public void setClaimReturnCode(java.lang.String claimReturnCode) {
		this.claimReturnCode = claimReturnCode;
	}

	public java.lang.Double getTotalClaimCoinsurance() {
		return this.totalClaimCoinsurance;
	}

	public void setTotalClaimCoinsurance(java.lang.Double totalClaimCoinsurance) {
		this.totalClaimCoinsurance = totalClaimCoinsurance;
	}

	public Claim(java.lang.String providerNumber, java.lang.String carrier,
			java.lang.String locality, java.lang.Double maPlanAmount,
			java.util.Date serviceFromDate, java.util.Date serviceThroughDate,
			java.lang.Double totalClaimPayment,
			java.lang.Double totalMedicareReimbursement,
			java.lang.String claimReturnCode,
			java.lang.Double totalClaimCoinsurance) {
		this.providerNumber = providerNumber;
		this.carrier = carrier;
		this.locality = locality;
		this.maPlanAmount = maPlanAmount;
		this.serviceFromDate = serviceFromDate;
		this.serviceThroughDate = serviceThroughDate;
		this.totalClaimPayment = totalClaimPayment;
		this.totalMedicareReimbursement = totalMedicareReimbursement;
		this.claimReturnCode = claimReturnCode;
		this.totalClaimCoinsurance = totalClaimCoinsurance;
	}

}