package gov.cms.fqhc_pricer;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MAPlan implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public MAPlan() {
    }




}