package gov.cms.fqhc_pricer;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Description("Object representing the fact that the plan is not an MA plan.")
public class NotMAPlan implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public NotMAPlan() {
	}

}